
package com.marlabs.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHello", targetNamespace = "http://soap.marlabs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://soap.marlabs.com/", className = "com.marlabs.soap.HelloWorld")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://soap.marlabs.com/", className = "com.marlabs.soap.HelloWorldResponse")
    @Action(input = "http://soap.marlabs.com/IHello/helloWorldRequest", output = "http://soap.marlabs.com/IHello/helloWorldResponse")
    public String helloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
